#!/bin/bash

################################################################################
# Quick Commands Reference for Pi-RAG Docker Deployment
################################################################################

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║          Pi-RAG Docker Deployment - Quick Commands Reference          ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ PREREQUISITES SETUP                                                │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "1. Set Docker context for Pi:"
echo "   docker context create pi --docker \"host=ssh://pi@<pi-ip>\""
echo "   docker context use pi"
echo ""
echo "2. Test connection:"
echo "   docker --context pi ps"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ AUTOMATED DEPLOYMENT                                               │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "./scripts/deploy.sh pi@<pi-ip>"
echo "   - Full automated deployment"
echo "   - Downloads embedding model"
echo "   - Builds Docker image"
echo "   - Starts container"
echo "   - Runs health checks"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ MANUAL DOCKER COMMANDS                                             │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Build and start:"
echo "   docker compose -f docker-compose.pi.yml --context pi up -d"
echo ""
echo "View logs:"
echo "   docker compose -f docker-compose.pi.yml --context pi logs -f"
echo ""
echo "Stop and remove:"
echo "   docker compose -f docker-compose.pi.yml --context pi down"
echo ""
echo "Rebuild without cache:"
echo "   docker compose -f docker-compose.pi.yml --context pi build --no-cache"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ CONTAINER OPERATIONS                                               │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Enter container:"
echo "   docker exec -it pi-rag bash"
echo ""
echo "View real-time stats:"
echo "   docker stats pi-rag"
echo ""
echo "Check health:"
echo "   docker inspect pi-rag --format='{{.State.Health.Status}}'"
echo ""
echo "Restart container:"
echo "   docker restart pi-rag"
echo ""
echo "Remove container:"
echo "   docker rm -f pi-rag"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TESTING THE API                                                    │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Health check:"
echo "   curl http://<pi-ip>:8001/health"
echo ""
echo "List models:"
echo "   curl http://<pi-ip>:8001/v1/models"
echo ""
echo "Get stats:"
echo "   curl http://<pi-ip>:8001/v1/stats"
echo ""
echo "Test RAG query:"
echo "   curl -X POST http://<pi-ip>:8001/v1/chat/completions \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"messages\": [{\"role\":\"user\",\"content\":\"Hello\"}]}'"
echo ""
echo "Search documents:"
echo "   curl -X POST http://<pi-ip>:8001/v1/search \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"query\": \"vector store\", \"top_k\": 5}'"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ INGESTING DOCUMENTS                                                │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Copy files to Pi:"
echo "   scp -r /local/docs pi@<pi-ip>:/home/pi/pi-rag-data/docs/"
echo ""
echo "Bulk ingest from container:"
echo "   docker exec pi-rag python -m rag.bulk_ingest /app/data/docs"
echo ""
echo "Ingest with options:"
echo "   docker exec pi-rag python -m rag.bulk_ingest \\"
echo "     /app/data/docs --tags \"source:my-docs\" --chunk-size 500"
echo ""
echo "Via API:"
echo "   curl -X POST http://<pi-ip>:8001/v1/ingest \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\": \"Your text\", \"source_name\": \"api\"}'"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ VOLUME MANAGEMENT                                                  │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "List volumes:"
echo "   docker volume ls | grep pi-rag"
echo ""
echo "Inspect volume:"
echo "   docker volume inspect pi-rag-data"
echo ""
echo "Backup data volume:"
echo "   docker run --rm -v pi-rag-data:/data -v \$(pwd):/backup alpine \\"
echo "     tar czf /backup/pi-rag-backup.tar.gz /data"
echo ""
echo "Remove volume (WARNING: deletes all data):"
echo "   docker volume rm pi-rag-data"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TROUBLESHOOTING                                                    │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Container won't start:"
echo "   docker logs pi-rag"
echo ""
echo "Check resource usage:"
echo "   docker exec pi-rag top"
echo "   docker exec pi-rag free -h"
echo ""
echo "Check model file:"
echo "   docker exec pi-rag ls -la /app/models/"
echo ""
echo "Test external API connectivity:"
echo "   docker exec pi-rag curl -v https://your-api-server:8443/health"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ PERFORMANCE MONITORING                                           │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Real-time container stats:"
echo "   docker stats pi-rag"
echo ""
echo "Check memory on Pi:"
echo "   ssh pi@<pi-ip> 'free -h'"
echo ""
echo "Check CPU usage:"
echo "   ssh pi@<pi-ip> 'top -b -n 1 | head -20'"
echo ""
echo "Docker system info:"
echo "   docker --context pi system df"
echo ""
echo ""
echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ UPDATE & MAINTENANCE                                             │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo ""
echo "Update to latest version:"
echo "   docker compose -f docker-compose.pi.yml --context pi build --no-cache"
echo "   docker compose -f docker-compose.pi.yml --context pi up -d"
echo ""
echo "Cleanup unused images:"
echo "   docker --context pi image prune -a"
echo ""
echo "Update Docker images:"
echo "   docker --context pi image pull python:3.11-slim"
echo ""
echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                    For detailed documentation, see:                  ║"
echo "║                    README-DOCKER.md                                  ║"
